"""Texas Hold'em equity + GTO solver."""

from poker_solver.abstraction.buckets import (
    AbstractionRef,
    AbstractionTables,
    load_abstraction,
    lookup_bucket,
    resolve_abstraction_ref,
    save_abstraction,
)
from poker_solver.abstraction.equity_features import canonicalize_for_suit_iso
from poker_solver.abstraction.precompute import build_abstraction
from poker_solver.action_abstraction import (
    ACTION_ALL_IN,
    ACTION_BET_33,
    ACTION_BET_75,
    ACTION_BET_100,
    ACTION_BET_150,
    ACTION_BET_200,
    ACTION_CALL,
    ACTION_CHECK,
    ACTION_FOLD,
    ACTION_RAISE_33,
    ACTION_RAISE_75,
    ACTION_RAISE_100,
    ACTION_RAISE_150,
    ACTION_RAISE_200,
    ActionAbstractionConfig,
    ActionContext,
    compute_bet_amount,
    compute_raise_to,
    enumerate_legal_actions,
)
from poker_solver.card import (
    RANKS,
    SUITS,
    Card,
    Deck,
    card_to_int,
    int_to_card,
    parse_board,
    parse_card,
    parse_hand,
)
from poker_solver.dcfr import DCFRSolver, InfosetData
from poker_solver.equity import EquityResult, equity
from poker_solver.evaluator import HandRank, evaluate
from poker_solver.games import (
    LEDUC_CALL,
    LEDUC_FOLD,
    LEDUC_RAISE,
    Game,
    KuhnPoker,
    KuhnState,
    LeducPoker,
    LeducState,
    kuhn_nash_value,
)
from poker_solver.hunl import (
    HUNLConfig,
    HUNLPoker,
    HUNLState,
    Street,
    default_tiny_subgame,
)
from poker_solver.hunl_solver import HUNLSolveResult, solve_hunl_postflop
from poker_solver.library import (
    Library,
    LibraryDuplicateError,
    LibraryError,
    LibraryFilter,
    LibrarySchemaError,
    LibraryStats,
    SpotDescription,
    SpotMetadata,
)
from poker_solver.preflop import (
    PREFLOP_MAX_BB,
    PreflopSolveResult,
    solve_hunl_preflop,
)
from poker_solver.profiler.memory import MemoryProbe, MemoryReport, StreetMemoryEntry
from poker_solver.pushfold import (
    PUSHFOLD_MAX_BB,
    PUSHFOLD_MIN_BB,
    PushFoldChartUnavailable,
    get_full_range,
    get_pushfold_range,
    get_pushfold_strategy,
    is_pushfold_mode,
    solve_pushfold,
)
from poker_solver.range import Range, parse_range
from poker_solver.range_aggregator import (
    DEFAULT_TIME_BUDGET_PER_SOLVE_S,
    RangeVsRangeNashResult,
    RangeVsRangeResult,
    solve_range_vs_range,
    solve_range_vs_range_nash,
)
from poker_solver.solver import SolveResult, exploitability, solve

__all__ = [
    "AbstractionRef",
    "AbstractionTables",
    "build_abstraction",
    "canonicalize_for_suit_iso",
    "load_abstraction",
    "lookup_bucket",
    "resolve_abstraction_ref",
    "save_abstraction",
    "Card",
    "Deck",
    "RANKS",
    "SUITS",
    "card_to_int",
    "int_to_card",
    "parse_card",
    "parse_hand",
    "parse_board",
    "HandRank",
    "evaluate",
    "EquityResult",
    "equity",
    "Range",
    "parse_range",
    "DEFAULT_TIME_BUDGET_PER_SOLVE_S",
    "RangeVsRangeNashResult",
    "RangeVsRangeResult",
    "solve_range_vs_range",
    "solve_range_vs_range_nash",
    "Game",
    "KuhnPoker",
    "KuhnState",
    "kuhn_nash_value",
    "LeducPoker",
    "LeducState",
    "LEDUC_FOLD",
    "LEDUC_CALL",
    "LEDUC_RAISE",
    "HUNLPoker",
    "HUNLState",
    "HUNLConfig",
    "HUNLSolveResult",
    "Street",
    "default_tiny_subgame",
    "solve_hunl_postflop",
    "PREFLOP_MAX_BB",
    "PreflopSolveResult",
    "solve_hunl_preflop",
    "MemoryProbe",
    "MemoryReport",
    "StreetMemoryEntry",
    "ActionContext",
    "ActionAbstractionConfig",
    "enumerate_legal_actions",
    "compute_bet_amount",
    "compute_raise_to",
    "ACTION_FOLD",
    "ACTION_CHECK",
    "ACTION_CALL",
    "ACTION_BET_33",
    "ACTION_BET_75",
    "ACTION_BET_100",
    "ACTION_BET_150",
    "ACTION_BET_200",
    "ACTION_RAISE_33",
    "ACTION_RAISE_75",
    "ACTION_RAISE_100",
    "ACTION_RAISE_150",
    "ACTION_RAISE_200",
    "ACTION_ALL_IN",
    "DCFRSolver",
    "InfosetData",
    "SolveResult",
    "solve",
    "exploitability",
    "get_pushfold_strategy",
    "get_full_range",
    "get_pushfold_range",
    "is_pushfold_mode",
    "solve_pushfold",
    "PushFoldChartUnavailable",
    "PUSHFOLD_MIN_BB",
    "PUSHFOLD_MAX_BB",
    "Library",
    "LibraryDuplicateError",
    "LibraryError",
    "LibraryFilter",
    "LibrarySchemaError",
    "LibraryStats",
    "SpotDescription",
    "SpotMetadata",
]

__version__ = "1.7.0"
